### PR TITLE
add multiline support to glua

### PR DESCRIPTION
**Pull request by xtaci**
I've added multiline support to glua, try this.

### CODE REVIEW

**Comment by xtaci** [comment]
And I think it's even better to embed  https://github.com/chzyer/readline  for command history.
Here's my program using readline: https://github.com/gonet2/archiver/blob/master/src/replay/main.go

**Comment by yuin** [comment]
Thanks for your PR and suggestions.
It seems your `incomplete` function uses some loose condition.
I think codes like the following are more appropriate.

```go
func incomplete(err error) bool {
	if lerr, ok := err.(*lua.ApiError); ok {
		if perr, ok := lerr.Cause.(*parse.Error); ok {
			return perr.Pos.Line == parse.EOF
		}
	}
	return false
}
```

**Comment by xtaci** [comment]
It's definitely better, I'll commit another PR.

**Comment by yuin** [comment]
Thanks for your quick response!

**Pull request merged**
