### PR TITLE
Implemented OpenXXX LGFunctions for each built-in module, refactored LState.OpenLibs

### PR DESCRIPTION
**Pull request by cathalgarvey**
WRT #55.

Apologies for the whitespace removal diff-noise, that was my editor..

### CODE REVIEW

**Comment by yuin** [comment]
Thanks for your PR.

Hmm, GopherLua is a Lua5.1 implementation, so you had better to read the original C implementation to implement features defined in Lua5.1

1.  `BaseLibName` should be `""` , `LoadLibName` should be `"package"` . see [lualib.h](http://www.lua.org/source/5.1/lualib.h.html)
2. `OpenLoad` should be `OpenPackage` .  see [linit.c](http://www.lua.org/source/5.1/linit.c.html)
2. `OpenXXX` should return a newly created module(an LTable object). example: [luaopen_os](http://www.lua.org/source/5.1/loslib.c.html#luaopen_os)
2. `LuaLibs` in `linit.go` should be a package local variable. see [linit.c](http://www.lua.org/source/5.1/linit.c.html), lualibs is a static.
3. It is better to change `LuaLibs` (should be `luaLibs`)  to a slice because order is important.
4. `OpenLibs` should use `Call` instead of `DoString` . see [linit.c](http://www.lua.org/source/5.1/linit.c.html)
5. Thanks for kindly comments. But GopherLua does not give comments for elements that has same name(but camelcased...) and same functionality with original Lua5.1. Could you remove your comments for now?

**Comment by cathalgarvey** [comment]
Can do! I added comments to satisfy my linter.. <_<

Will get this done this evening, UTC.

**Comment by yuin** [comment]
And...

- `OpenLibs` should not use `PreloadModule` . see linit.c

```c
    lua_pushcfunction(L, lib->func);
    lua_pushstring(L, lib->name);
    lua_call(L, 1, 0);
```

- `OpenXXX` should take 1 string argument(`lib->name`). (This argument looks like it is not used in `OpenXXX` though...)

**Comment by cathalgarvey** [comment]
Hmm.. do you want me to be consistent with Lua5.1 even when it makes no sense, like OpenXXX not using string arguments? Or do what the user expects, and use the string argument as the module name?

**Comment by cathalgarvey** [comment]
Made requested changes, as I understood them. :)

**Comment by yuin** [comment]
Great job.

Sorry for not being able to point problems out all at once.

- `luaopen_xxx` uses `LUA_XXXLIBNAME` to create a new module. Could you change `OpenXXX` in the same way?
- It seems that `OpenChannel` and `OpenString` sometimes return a nil value. Could you remove ` if !ok {` guard?

**Comment by cathalgarvey** [comment]
Can modify them to register modules using the hard-coded names, yes. 

I don't pretend to have your knowledge of the modules: will removing the `if ok{` guard require other changes to keep things safe?

On 20 January 2016 14:27:30 GMT+00:00, Yusuke Inuzuka <notifications@github.com> wrote:
>Great job.
>
>Sorry for not being able to point problems out all at once.
>
>- `luaopen_xxx` uses `LUA_XXXLIBNAME` to create a new module. Could you
>change `OpenXXX` in the same way?
>- It seems that `OpenChannel` and `OpenString` sometimes return a nil
>value. Could you remove ` if !ok {` guard?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/yuin/gopher-lua/pull/60#issuecomment-173220240

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by yuin** [comment]
> will removing the `if ok{` guard require other changes to keep things safe?

No other changes required, Calling `OpenString` (or `OpenChannel`) twice is just wasteful, but harmless.

**Comment by cathalgarvey** [comment]
I don't know about what happened to OpenChannel, but I found a bug I'd introduced to OpenString: mod was declared an LValue but shadowed in the if-block.

On 20 January 2016 14:27:30 GMT+00:00, Yusuke Inuzuka <notifications@github.com> wrote:
>Great job.
>
>Sorry for not being able to point problems out all at once.
>
>- `luaopen_xxx` uses `LUA_XXXLIBNAME` to create a new module. Could you
>change `OpenXXX` in the same way?
>- It seems that `OpenChannel` and `OpenString` sometimes return a nil
>value. Could you remove ` if !ok {` guard?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/yuin/gopher-lua/pull/60#issuecomment-173220240

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by yuin** [comment]
> but I found a bug I'd introduced to OpenString: mod was declared an LValue but shadowed in the if-block.

Oh, just so...

**Comment by cathalgarvey** [comment]
I've been using `go test` prior to every push, so if `string` wasn't registering sometimes (only sometimes?), it didn't get picked up. I'm glad you noticed!

**Comment by yuin** [comment]
LGTM, I will merge this PR and make some adjustments.
Thanks for your contribution :+1:

**Comment by cathalgarvey** [comment]
Thank you! Glad to have this facility mainlined, it will make my Lua security much easier to reason about. :)

On 20 January 2016 15:38:56 GMT+00:00, Yusuke Inuzuka <notifications@github.com> wrote:
>LGTM, I will merge this PR and make some adjustments.
>Thanks for your contribution :+1: 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/yuin/gopher-lua/pull/60#issuecomment-173242429

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request merged**
